import { themeColors } from "./color";
export const adminFeatures = [
  {
    id: "1",
    title: "User Management",
    icon: "people",
    description: "Manage registered users and activities",
    color: themeColors.primary,
    component: "UserManagement",
  },
  {
    id: "2",
    title: "Book & Content",
    icon: "menu-book",
    description: "Manage books, categories, PDFs, and metadata",
    color: themeColors.warning,
    component: "BookManagement",
  },
  {
    id: "3",
    title: "Payments",
    icon: "payments",
    description: "View and manage transactions & refunds",
    color: themeColors.success,
    component: "Payments",
  },
  {
    id: "4",
    title: "Notifications",
    icon: "notifications",
    description: "Send announcements & manage history",
    color: themeColors.danger,
    component: "Notifications",
  },
  // {
  //   id: "5",
  //   title: "App Settings",
  //   icon: "settings",
  //   description: "Update app info, policies & terms",
  //   color: themeColors.accent,
  //   component: "AppSettings",
  // },
  // {
  //   id: "6",
  //   title: "Support & Feedback",
  //   icon: "support-agent",
  //   description: "Respond to user requests and manage FAQs",
  //   color: themeColors.gradientMiddle,
  //   component: "Support",
  // },
  {
    id: "7",
    title: "Analytics & Reports",
    icon: "analytics",
    description: "View usage, sales & engagement insights",
    color: themeColors.gradientEnd,
    component: "Analytics",
  },
  {
    id: "8",
    title: "Category Management",
    icon: "category",
    description: "Manage book categories and metadata",
    color: themeColors.textPrimary,
    component: "CategoryManagement",
  },
];